### ISSUE TITLE
Misleading "Incorrect username/email or password" UI

### ISSUE THREAD

**Issue by ILM126** [ProfilerTeam/Profiler#13]
When I input the wrong username, the password input box came back highlighted red. But I would suggest that both box be highlighted when this occur...

[Screenshot of screen](http://i.imgur.com/v2Mj9Uj.png)

**Comment by Member1221** [comment]
Will fix asap.

**Comment by Member1221** [comment]
@ILM126 This has been fixed with commit https://github.com/ProfilerTeam/Profiler/commit/81ae17a37004e64fccf2cbeeb4460e93bcd68fb5. c:
