### ISSUE TITLE
Last name

### ISSUE THREAD

**Issue by AppleJack111** [ProfilerTeam/Profiler#14]
Can't type in "<3, also it need to be filled with 1 or more Letter (Numbers dont work, either does special characters) other wise it is blank

**Comment by Member1221** [comment]
will look at.

**Comment by Member1221** [comment]
I've done some changes to the db structure, instead of firstname and lastname. name will be used. name can contain spaces, and special characters.
Will push that asap.

**Comment by Member1221** [comment]
Fixed in commit https://github.com/ProfilerTeam/Profiler/commit/131e7aba7ee6b628313fcc6246b4a0a2bdf92443 @AppleJack111
