### ISSUE TITLE
Remove the old prealpha bottom bar

### ISSUE THREAD

**Issue by LunaTheFoxgirl** [ProfilerTeam/Profiler#16]
![The bar in question](https://cloud.githubusercontent.com/assets/7032834/20237059/21eafa18-a8c8-11e6-8b19-14d0bbfa816d.png)
This needs to be removed, and the search button fixed, and moved up to the top bar, preferably beside the user avatar.

**Comment by Member1221** [comment]
Fixed in https://github.com/ProfilerTeam/Profiler/commit/bb7f00b820e842ece69fa69bbf6b8ce555e9aec4
